<a href="https://colab.research.google.com/github/meeks627/Pytorch-Tutorial/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d
# tensor_2d.dtype

tensor([[-0.3781, -1.2492,  2.0396, -0.2836],
        [-0.4907,  0.5605,  1.1981,  1.0539],
        [-0.6266, -1.5251, -0.9607, -2.3335]])

In [ ]:
tensor_3d= torch.randn(2,3,4)
tensor_3d

tensor([[[ 0.3513, -0.2110, -0.2146,  0.4679],
         [ 0.4851,  0.4067, -0.3137,  1.2015],
         [ 0.1950,  1.9752,  0.4794,  0.7118]],

        [[-0.4210, -1.3916,  0.1215,  0.5508],
         [ 0.6849,  0.9296,  1.0492, -0.4004],
         [ 0.2076,  0.2792, -0.8122,  1.1106]]])

###Tensor from Numpy

In [ ]:
data = [[3,4],[8,11]]
xdata = np.array(data)
data_t = torch.tensor(data)
print(xdata)
print(data_t)
print(torch.from_numpy(xdata))
print(torch.ones_like(data_t))
print(torch.zeros_like(data_t))


[[ 3  4]
 [ 8 11]]
tensor([[ 3,  4],
        [ 8, 11]])
tensor([[ 3,  4],
        [ 8, 11]])
tensor([[1, 1],
        [1, 1]])
tensor([[0, 0],
        [0, 0]])


##Tensor Operation

In [ ]:
my_tensor = torch.arange(20)
my_tensor.reshape(4,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [ ]:
my_tensor2 = torch.arange(20).reshape(2,2,5)
print(my_tensor2)
print(my_tensor2[:,1,1:-1])
print(my_tensor2[0,0:2,0:2])


tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]])
tensor([[ 6,  7,  8],
        [16, 17, 18]])
tensor([[0, 1],
        [5, 6]])


In [ ]:
Var1 = torch.randint(1,10,(2,2))
Var2 = torch.randint(1,10,(2,2))
print(torch.add(Var1,Var2))
print(torch.sub(Var1,Var2))
print(torch.mul(Var1,Var2))
print(torch.div(Var1,Var2))

tensor([[13, 13],
        [ 7,  6]])
tensor([[-5, -5],
        [-5,  0]])
tensor([[36, 36],
        [ 6,  9]])
tensor([[0.4444, 0.4444],
        [0.1667, 1.0000]])


##Building a Simple model

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class Model(nn.Module):
  def __init__(self,in_size=2,h1=10,h2=5,out_size=2):
    super().__init__()
    self.w1 = nn.Linear(in_size,h1)
    self.w2 = nn.Linear(h1,h2)
    self.out = nn.Linear(h2,out_size)
  def forward(self,x):
    X = F.relu(self.w1(x))
    X = F.relu(self.w2(X))
    X = self.out(X)
    return X

M = Model()
points = torch.randn(40,2)
M.forward(points)
# print(M.w1.weight[1,1])
# print(M.w1.bias)
torch.save(M.state_dict(),'model.pt')